# Travis CI checks for atomicapp

language: python

python:
  - "2.7"

notifications:
  irc: "chat.freenode.net#nulecule"

before_install:
  - pip install pytest-cov coveralls --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install flake8 --use-mirrors 

install:
  - make install

before_script:
  - make syntax-check

script:
  - make test

after_success:
  - coveralls
