language: python
python:
  - "2.7"
notifications:
  irc: "chat.freenode.net#nulecule"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
script:
  python -m pytest -vv tests --cov atomicapp
after_success:
  coveralls
